name: ecommerce_sneaker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.0.2
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter_svg: ^2.0.1
  image_picker: ^1.0.4
  intl: ^0.17.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^6.1.5
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.jpg
    - assets/images/banner4.jpg
    - assets/images/default_avatar.jpg
